spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:hospitalai;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql
