DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS knowledge_submission_review;
DROP TABLE IF EXISTS knowledge_submission;
DROP TABLE IF EXISTS research_deidentified_export;
DROP TABLE IF EXISTS research_analysis_run;
DROP TABLE IF EXISTS prescription_draft_write_task;
DROP TABLE IF EXISTS prescription_draft;
DROP TABLE IF EXISTS collaboration_task;
DROP TABLE IF EXISTS pharmacist_review_task;
DROP TABLE IF EXISTS recommendation_snapshot;
DROP TABLE IF EXISTS recommendation_decision;
DROP TABLE IF EXISTS rule_execution;
DROP TABLE IF EXISTS evidence_chunk;
DROP TABLE IF EXISTS document_block;
DROP TABLE IF EXISTS dose_rule;
DROP TABLE IF EXISTS clinical_rule_case;
DROP TABLE IF EXISTS clinical_rule;
DROP TABLE IF EXISTS evidence_document;
DROP TABLE IF EXISTS drug_catalog;
DROP TABLE IF EXISTS adverse_drug_reaction;
DROP TABLE IF EXISTS allergy_event;
DROP TABLE IF EXISTS medication_exposure;
DROP TABLE IF EXISTS medication_order;
DROP TABLE IF EXISTS lab_result;
DROP TABLE IF EXISTS diagnosis;
DROP TABLE IF EXISTS source_sync_cursor;
DROP TABLE IF EXISTS inbound_event;
DROP TABLE IF EXISTS source_identifier_mapping;
DROP TABLE IF EXISTS department_participation;
DROP TABLE IF EXISTS encounters;
DROP TABLE IF EXISTS patients;
DROP TABLE IF EXISTS research_report_draft;
DROP TABLE IF EXISTS research_dataset_quality_check;
DROP TABLE IF EXISTS research_variable;
DROP TABLE IF EXISTS research_cohort;
DROP TABLE IF EXISTS discharge_outcome;
DROP TABLE IF EXISTS medication_feedback;
DROP TABLE IF EXISTS medication_timeline_event;

CREATE TABLE patients (patient_id TEXT PRIMARY KEY, his_patient_id TEXT NOT NULL, display_name TEXT NOT NULL, sex TEXT NOT NULL, age INT NOT NULL);
CREATE TABLE encounters (encounter_id TEXT PRIMARY KEY, patient_id TEXT NOT NULL, department TEXT NOT NULL, diagnosis TEXT NOT NULL, scenario TEXT NOT NULL, data_version INT NOT NULL, admitted_at TIMESTAMP NOT NULL);
CREATE TABLE department_participation (id TEXT PRIMARY KEY, encounter_id TEXT NOT NULL, department TEXT NOT NULL, role TEXT NOT NULL, doctor_name TEXT NOT NULL, active BOOLEAN NOT NULL);
CREATE TABLE source_identifier_mapping (internal_id TEXT NOT NULL, source_system TEXT NOT NULL, source_id TEXT NOT NULL, object_type TEXT NOT NULL, version INT NOT NULL);
CREATE TABLE inbound_event (event_id TEXT PRIMARY KEY, source_system TEXT NOT NULL, source_batch_id TEXT NOT NULL, event_type TEXT NOT NULL, status TEXT NOT NULL, payload_version TEXT NOT NULL, payload_hash TEXT NOT NULL, error_message TEXT, received_at TIMESTAMP NOT NULL, applied_at TIMESTAMP, UNIQUE (source_system, source_batch_id, event_type));
CREATE TABLE source_sync_cursor (source_system TEXT NOT NULL, stream_name TEXT NOT NULL, cursor_value TEXT NOT NULL, updated_at TIMESTAMP NOT NULL, PRIMARY KEY (source_system, stream_name));
CREATE TABLE diagnosis (id TEXT PRIMARY KEY, encounter_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL, source_id TEXT NOT NULL, collected_at TIMESTAMP NOT NULL);
CREATE TABLE lab_result (id TEXT PRIMARY KEY, encounter_id TEXT NOT NULL, code TEXT NOT NULL, name TEXT NOT NULL, lab_value TEXT, unit TEXT, missing_status TEXT NOT NULL, source_id TEXT NOT NULL, collected_at TIMESTAMP NOT NULL);
CREATE TABLE medication_order (id TEXT PRIMARY KEY, encounter_id TEXT NOT NULL, patient_id TEXT NOT NULL, drug_code TEXT NOT NULL, drug_name TEXT NOT NULL, pharmacology_class TEXT NOT NULL, department TEXT NOT NULL, status TEXT NOT NULL, source_id TEXT NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE medication_exposure (id TEXT PRIMARY KEY, patient_id TEXT NOT NULL, encounter_id TEXT NOT NULL, drug_code TEXT NOT NULL, drug_name TEXT NOT NULL, started_at TIMESTAMP NOT NULL, ended_at TIMESTAMP);
CREATE TABLE medication_timeline_event (event_id TEXT PRIMARY KEY, patient_id TEXT NOT NULL, encounter_id TEXT NOT NULL, event_type TEXT NOT NULL, drug_code TEXT, drug_name TEXT, event_time TIMESTAMP NOT NULL, source_system TEXT NOT NULL, source_id TEXT NOT NULL, detail TEXT NOT NULL);
CREATE TABLE medication_feedback (feedback_id TEXT PRIMARY KEY, patient_id TEXT NOT NULL, encounter_id TEXT NOT NULL, drug_code TEXT NOT NULL, effectiveness TEXT NOT NULL, adverse_signal TEXT NOT NULL, reporter_role TEXT NOT NULL, note TEXT NOT NULL, recorded_at TIMESTAMP NOT NULL);
CREATE TABLE discharge_outcome (outcome_id TEXT PRIMARY KEY, patient_id TEXT NOT NULL, encounter_id TEXT NOT NULL, outcome_status TEXT NOT NULL, readmission_risk TEXT NOT NULL, followup_required BOOLEAN NOT NULL, note TEXT NOT NULL, recorded_at TIMESTAMP NOT NULL);
CREATE TABLE allergy_event (id TEXT PRIMARY KEY, patient_id TEXT NOT NULL, drug_code TEXT NOT NULL, drug_name TEXT NOT NULL, status TEXT NOT NULL, severity TEXT NOT NULL, source_id TEXT NOT NULL, confirmed_at TIMESTAMP);
CREATE TABLE adverse_drug_reaction (id TEXT PRIMARY KEY, patient_id TEXT NOT NULL, drug_code TEXT NOT NULL, drug_name TEXT NOT NULL, severity TEXT NOT NULL, review_status TEXT NOT NULL, source_id TEXT NOT NULL, reviewed_at TIMESTAMP);
CREATE TABLE drug_catalog (drug_code TEXT PRIMARY KEY, name TEXT NOT NULL, pharmacology_class TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE evidence_document (evidence_id TEXT PRIMARY KEY, title TEXT NOT NULL, status TEXT NOT NULL, version TEXT NOT NULL, effective_date DATE NOT NULL, scope TEXT NOT NULL, locator TEXT NOT NULL, text TEXT NOT NULL);
CREATE TABLE clinical_rule (rule_id TEXT NOT NULL, version TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL, severity TEXT NOT NULL, basis TEXT NOT NULL, deterministic_handler TEXT NOT NULL, published_at TIMESTAMP, PRIMARY KEY (rule_id, version));
CREATE TABLE clinical_rule_case (case_id TEXT PRIMARY KEY, rule_id TEXT NOT NULL, rule_version TEXT NOT NULL, title TEXT NOT NULL, input_ref TEXT NOT NULL, expected_result TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE dose_rule (dose_rule_id TEXT PRIMARY KEY, drug_code TEXT NOT NULL, indication TEXT NOT NULL, patient_group TEXT NOT NULL, renal_adjustment_required BOOLEAN NOT NULL, regimen_text TEXT NOT NULL, status TEXT NOT NULL, evidence_id TEXT, version TEXT NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE rule_execution (execution_id TEXT PRIMARY KEY, recommendation_id TEXT NOT NULL, encounter_id TEXT NOT NULL, rule_id TEXT NOT NULL, rule_version TEXT NOT NULL, result_level TEXT NOT NULL, blocked BOOLEAN NOT NULL, matched_facts TEXT NOT NULL, message TEXT NOT NULL, executed_at TIMESTAMP NOT NULL);
CREATE TABLE document_block (block_id TEXT PRIMARY KEY, evidence_id TEXT NOT NULL, block_type TEXT NOT NULL, page_label TEXT NOT NULL, sort_order INT NOT NULL, text TEXT NOT NULL);
CREATE TABLE evidence_chunk (chunk_id TEXT PRIMARY KEY, evidence_id TEXT NOT NULL, block_id TEXT NOT NULL, chunk_text TEXT NOT NULL, keywords TEXT NOT NULL, status TEXT NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE recommendation_decision (decision_id TEXT PRIMARY KEY, recommendation_id TEXT NOT NULL, encounter_id TEXT NOT NULL, candidate_id TEXT NOT NULL, action TEXT NOT NULL, original_version TEXT NOT NULL, modified_regimen TEXT, modified_diff_json TEXT, reason TEXT NOT NULL, actor TEXT NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE recommendation_snapshot (recommendation_id TEXT PRIMARY KEY, encounter_id TEXT NOT NULL, patient_id TEXT NOT NULL, data_version INT NOT NULL, status TEXT NOT NULL, candidate_count INT NOT NULL, blocking_count INT NOT NULL, strong_alert_count INT NOT NULL, generated_at TIMESTAMP NOT NULL, expired_at TIMESTAMP);
CREATE TABLE pharmacist_review_task (review_id TEXT PRIMARY KEY, recommendation_id TEXT NOT NULL, decision_id TEXT, encounter_id TEXT NOT NULL, status TEXT NOT NULL, priority TEXT NOT NULL, reason TEXT NOT NULL, assigned_role TEXT NOT NULL, created_at TIMESTAMP NOT NULL, resolved_at TIMESTAMP, resolution TEXT);
CREATE TABLE collaboration_task (task_id TEXT PRIMARY KEY, recommendation_id TEXT NOT NULL, encounter_id TEXT NOT NULL, source_department TEXT NOT NULL, target_department TEXT NOT NULL, status TEXT NOT NULL, reason TEXT NOT NULL, created_at TIMESTAMP NOT NULL, resolved_at TIMESTAMP, resolution TEXT);
CREATE TABLE prescription_draft (draft_id TEXT PRIMARY KEY, decision_id TEXT NOT NULL, encounter_id TEXT NOT NULL, status TEXT NOT NULL, idempotency_key TEXT NOT NULL, created_at TIMESTAMP NOT NULL, his_status TEXT, his_message TEXT, callback_at TIMESTAMP, UNIQUE (idempotency_key));
CREATE TABLE prescription_draft_write_task (task_id TEXT PRIMARY KEY, draft_id TEXT NOT NULL, status TEXT NOT NULL, attempt_count INT NOT NULL, next_attempt_at TIMESTAMP NOT NULL, last_error TEXT, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL);
CREATE TABLE audit_log (audit_id TEXT PRIMARY KEY, actor TEXT NOT NULL, action TEXT NOT NULL, object_id TEXT NOT NULL, detail TEXT NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE research_cohort (cohort_id TEXT PRIMARY KEY, name TEXT NOT NULL, disease_scope TEXT NOT NULL, inclusion_criteria TEXT NOT NULL, exclusion_criteria TEXT NOT NULL, status TEXT NOT NULL, created_at TIMESTAMP NOT NULL, frozen_at TIMESTAMP);
CREATE TABLE research_variable (variable_id TEXT PRIMARY KEY, cohort_id TEXT NOT NULL, name TEXT NOT NULL, definition TEXT NOT NULL, source_table TEXT NOT NULL, missing_policy TEXT NOT NULL, version TEXT NOT NULL);
CREATE TABLE research_dataset_quality_check (check_id TEXT PRIMARY KEY, cohort_id TEXT NOT NULL, status TEXT NOT NULL, total_subjects INT NOT NULL, missing_summary TEXT NOT NULL, issue_summary TEXT NOT NULL, checked_at TIMESTAMP NOT NULL);
CREATE TABLE research_analysis_run (run_id TEXT PRIMARY KEY, cohort_id TEXT NOT NULL, status TEXT NOT NULL, script_version TEXT NOT NULL, statistic_plan TEXT NOT NULL, input_hash TEXT NOT NULL, output_hash TEXT NOT NULL, result_summary TEXT NOT NULL, artifact_uri TEXT NOT NULL, started_at TIMESTAMP NOT NULL, completed_at TIMESTAMP);
CREATE TABLE research_deidentified_export (export_id TEXT PRIMARY KEY, cohort_id TEXT NOT NULL, status TEXT NOT NULL, row_count INT NOT NULL, artifact_uri TEXT NOT NULL, data_hash TEXT NOT NULL, requested_by TEXT NOT NULL, purpose TEXT NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE research_report_draft (report_id TEXT PRIMARY KEY, cohort_id TEXT NOT NULL, status TEXT NOT NULL, title TEXT NOT NULL, markdown_body TEXT NOT NULL, generated_at TIMESTAMP NOT NULL, reviewed_at TIMESTAMP, review_note TEXT);
CREATE TABLE knowledge_submission (submission_id TEXT PRIMARY KEY, report_id TEXT NOT NULL, status TEXT NOT NULL, submission_type TEXT NOT NULL, title TEXT NOT NULL, submitted_by TEXT NOT NULL, submitted_at TIMESTAMP NOT NULL, published_at TIMESTAMP);
CREATE TABLE knowledge_submission_review (review_id TEXT PRIMARY KEY, submission_id TEXT NOT NULL, reviewer_role TEXT NOT NULL, decision TEXT NOT NULL, note TEXT NOT NULL, reviewed_at TIMESTAMP NOT NULL);
