<template>
  <div class="product-page">
    <header class="page-heading"><div><h1>证据资料中心</h1><p>管理指南、说明书、临床路径与院内制度，从原始文件到可引用片段全程保留版本、哈希和定位。</p></div><div class="page-heading-actions"><el-button :icon="FolderSearch">人工处理队列 <span class="action-count">3</span></el-button><el-button type="primary" :icon="Upload" @click="uploadVisible=true">上传资料</el-button></div></header>
    <section class="summary-strip"><div class="summary-item"><div class="summary-icon"><Library :size="18" /></div><div><strong>42</strong><span>已发布资料</span></div></div><div class="summary-item"><div class="summary-icon warning"><ScanText :size="18" /></div><div><strong>5</strong><span>解析或元数据处理中</span></div></div><div class="summary-item"><div class="summary-icon blue"><FileCheck2 :size="18" /></div><div><strong>8,426</strong><span>可检索证据片段</span></div></div><div class="summary-item"><div class="summary-icon danger"><FileWarning :size="18" /></div><div><strong>3</strong><span>低置信度待人工处理</span></div></div></section>
    <div class="toolbar-band"><el-input v-model="query" :prefix-icon="Search" placeholder="资料名称、版本、适用范围" clearable/><el-select v-model="type"><el-option label="全部类型" value="all"/><el-option label="指南" value="guideline"/><el-option label="说明书" value="label"/><el-option label="院内制度" value="policy"/><el-option label="临床路径" value="pathway"/></el-select><el-select v-model="status"><el-option label="全部状态" value="all"/><el-option label="已发布" value="published"/><el-option label="待审核" value="review"/><el-option label="解析中" value="parsing"/><el-option label="已撤回" value="withdrawn"/></el-select><span class="toolbar-spacer"></span><el-button :icon="RefreshCw">同步状态</el-button></div>
    <div class="evidence-layout"><section class="surface-panel document-list"><div class="surface-panel-header"><h2>资料与版本</h2><span>{{ filteredDocs.length }} 份</span></div><table class="dense-table"><thead><tr><th>资料名称</th><th>类型 / 范围</th><th>版本</th><th>状态</th><th>解析质量</th><th>片段</th><th>更新时间</th></tr></thead><tbody><tr v-for="doc in filteredDocs" :key="doc.id" :class="{selected:selectedId===doc.id}" @click="selectedId=doc.id"><td><div class="doc-title"><FileText :size="16"/><div><strong>{{ doc.title }}</strong><small>{{ doc.id }} · {{ doc.format }}</small></div></div></td><td><span>{{ doc.typeLabel }}</span><small>{{ doc.scope }}</small></td><td><strong>{{ doc.version }}</strong><small>生效 {{ doc.effective }}</small></td><td><span class="status-pill" :class="doc.statusClass"><span class="dot"></span>{{ doc.statusLabel }}</span></td><td><strong>{{ doc.quality }}</strong><small>{{ doc.qualityNote }}</small></td><td>{{ doc.chunks }}</td><td><span>{{ doc.updatedAt }}</span><small>{{ doc.updatedBy }}</small></td></tr></tbody></table></section><aside v-if="selected" class="surface-panel evidence-inspector"><div class="inspector-heading"><div><span class="status-pill" :class="selected.statusClass"><span class="dot"></span>{{ selected.statusLabel }}</span><h2>{{ selected.title }}</h2><p>{{ selected.id }} · {{ selected.version }}</p></div><el-dropdown><el-button :icon="MoreHorizontal" circle/><template #dropdown><el-dropdown-menu><el-dropdown-item>下载原始文件</el-dropdown-item><el-dropdown-item>查看全部版本</el-dropdown-item><el-dropdown-item divided>发起撤回</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div><div class="document-meta"><div><span>SHA-256</span><strong>8ec4b6...73a912</strong></div><div><span>适用范围</span><strong>{{ selected.scope }}</strong></div><div><span>原始文件</span><strong>{{ selected.format }} · 2.8 MB</strong></div><div><span>生效日期</span><strong>{{ selected.effective }}</strong></div></div><el-tabs v-model="inspectorTab"><el-tab-pane label="证据片段" name="chunks"><div class="chunk-search"><el-input :prefix-icon="Search" placeholder="在当前资料内搜索"/><el-button :icon="ListFilter" circle/></div><article v-for="chunk in chunks" :key="chunk.locator" class="evidence-chunk"><div><span>{{ chunk.section }}</span><small>相关度 {{ chunk.score }}</small></div><p>{{ chunk.text }}</p><footer><span><MapPin :size="12"/>{{ chunk.locator }}</span><el-button size="small" :icon="ScanSearch">原文定位</el-button></footer></article></el-tab-pane><el-tab-pane label="处理记录" name="history"><div class="processing-steps"><div v-for="step in processingSteps" :key="step.name" :class="step.state"><component :is="step.state==='done'?CircleCheck:step.state==='active'?LoaderCircle:Circle" :size="16"/><span><strong>{{ step.name }}</strong><small>{{ step.detail }}</small></span></div></div></el-tab-pane></el-tabs></aside></div>
    <el-dialog v-model="uploadVisible" title="上传证据资料" width="680px"><el-upload drag action="#" :auto-upload="false" accept=".pdf,.docx,.xlsx,.txt,.md,image/*"><UploadCloud :size="30"/><div class="el-upload__text">拖放资料到此处，或 <em>选择本地文件</em></div><template #tip><div class="el-upload__tip">支持 PDF、扫描图片、DOCX、XLSX、TXT 和 Markdown。上传后先进入安全检查，不会直接参与推荐。</div></template></el-upload><div class="upload-fields"><el-form label-position="top"><div class="form-grid"><el-form-item label="资料类型"><el-select><el-option label="指南" value="guideline"/><el-option label="药品说明书" value="label"/><el-option label="院内制度" value="policy"/></el-select></el-form-item><el-form-item label="适用范围"><el-input placeholder="病种、科室或全院"/></el-form-item></div><el-form-item label="版本说明"><el-input placeholder="版本号、生效日期或替代关系"/></el-form-item></el-form></div><template #footer><el-button @click="uploadVisible=false">取消</el-button><el-button type="primary" @click="uploadVisible=false">进入安全检查</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'
import { Circle, CircleCheck, FileCheck2, FileText, FileWarning, FolderSearch, Library, ListFilter, LoaderCircle, MapPin, MoreHorizontal, RefreshCw, ScanSearch, ScanText, Search, Upload, UploadCloud } from 'lucide-vue-next'
const query=ref(''),type=ref('all'),status=ref('all'),selectedId=ref('EV-CAP-001'),inspectorTab=ref('chunks'),uploadVisible=ref(false)
const docs=[
 {id:'EV-CAP-001',title:'成人社区获得性肺炎院内诊疗路径',format:'PDF',type:'pathway',typeLabel:'临床路径',scope:'呼吸内科 · 住院成人',version:'v2026.08',effective:'2026-08-01',status:'published',statusLabel:'已发布',statusClass:'',quality:'98.6%',qualityNote:'版面解析通过',chunks:186,updatedAt:'08-02 10:18',updatedBy:'陈药师'},
 {id:'EV-LABEL-AMOX',title:'阿莫西林克拉维酸钾药品说明书',format:'PDF',type:'label',typeLabel:'说明书',scope:'全院 · 抗感染药',version:'核准 2025-12',effective:'2025-12-16',status:'published',statusLabel:'已发布',statusClass:'',quality:'99.2%',qualityNote:'表格人工复核',chunks:94,updatedAt:'08-01 14:20',updatedBy:'资料管理员'},
 {id:'EV-POLICY-ADR',title:'药品不良反应报告与处置制度',format:'DOCX',type:'policy',typeLabel:'院内制度',scope:'全院',version:'v4.2',effective:'2026-06-01',status:'published',statusLabel:'已发布',statusClass:'',quality:'97.4%',qualityNote:'结构解析通过',chunks:72,updatedAt:'07-28 09:12',updatedBy:'药学部'},
 {id:'EV-CAP-NEW',title:'CAP 指南更新候选稿',format:'PDF',type:'guideline',typeLabel:'指南',scope:'呼吸内科',version:'2026 draft',effective:'待确认',status:'review',statusLabel:'待审核',statusClass:'warning',quality:'95.1%',qualityNote:'3 个表格待复核',chunks:214,updatedAt:'08-03 09:45',updatedBy:'周医生'},
 {id:'EV-SCAN-014',title:'抗菌药物管理制度扫描件',format:'扫描 PDF',type:'policy',typeLabel:'院内制度',scope:'全院',version:'未知',effective:'待补充',status:'parsing',statusLabel:'待补元数据',statusClass:'info',quality:'72.8%',qualityNote:'低置信度',chunks:0,updatedAt:'08-03 10:02',updatedBy:'资料管理员'}
]
const filteredDocs=computed(()=>docs.filter(d=>(!query.value||`${d.title}${d.id}${d.scope}`.includes(query.value))&&(type.value==='all'||d.type===type.value)&&(status.value==='all'||d.status===status.value)))
const selected=computed(()=>docs.find(d=>d.id===selectedId.value)??docs[0])
const chunks=[{section:'初始经验性治疗',score:'92%',locator:'第 6 页 · 2.3 节 · 第 2 段',text:'候选方案应结合患者既往过敏、不良反应、肝肾功能与当前有效用药进行比较；存在确定性阻断时不得进入正常提交。'},{section:'治疗监测',score:'88%',locator:'第 9 页 · 表 4 · 第 2 行',text:'处方前核对关键检验和当前用药。检验缺失应显示未知状态，不得以正常值代替。'}]
const processingSteps=[{name:'原始文件安全检查',detail:'SHA-256 已计算 · 类型校验通过',state:'done'},{name:'文档解析与版面识别',detail:'186 个块 · 12 张表格',state:'done'},{name:'证据切分与元数据',detail:'186 个片段 · 定位完整',state:'done'},{name:'药师专业审核',detail:'陈药师 · 2026-08-02',state:'done'},{name:'发布至正式证据库',detail:'2026-08-02 10:18',state:'done'}]
</script>
<style scoped>
.action-count{display:inline-grid;place-items:center;min-width:17px;height:17px;margin-left:3px;border-radius:9px;background:#bd2f37;color:#fff;font-size:8px}.evidence-layout{display:grid;grid-template-columns:minmax(650px,64%) minmax(320px,36%);gap:12px}.document-list{overflow-x:auto}.document-list table{min-width:820px}.document-list tbody tr{cursor:pointer}.document-list tbody tr.selected{background:#edf5f4;box-shadow:inset 3px 0 0 #126b66}.doc-title{display:flex;align-items:flex-start;gap:7px;max-width:220px}.doc-title>div{min-width:0}.doc-title strong,.document-list td small{display:block}.doc-title strong{font-size:10px;line-height:1.4}.document-list td small{margin-top:3px;color:#73828a;font-size:8px}.evidence-inspector{min-width:0;padding:13px}.inspector-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;padding-bottom:11px;border-bottom:1px solid #dce4e7}.inspector-heading h2{margin:7px 0 3px;font-size:14px;line-height:1.35}.inspector-heading p{margin:0;color:#6b7a82;font-size:8px}.document-meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:11px 0}.document-meta>div{display:grid;gap:2px;padding:8px;background:#f4f7f8}.document-meta span{color:#728088;font-size:8px}.document-meta strong{overflow-wrap:anywhere;font-size:9px}.chunk-search{display:grid;grid-template-columns:1fr auto;gap:6px;margin-bottom:8px}.evidence-chunk{margin-bottom:8px;padding:10px;border:1px solid #d8e1e4;border-radius:5px}.evidence-chunk>div,.evidence-chunk footer{display:flex;align-items:center;justify-content:space-between;gap:8px}.evidence-chunk>div span{color:#126b66;font-size:8px;font-weight:750}.evidence-chunk small{color:#78868d;font-size:8px}.evidence-chunk p{margin:8px 0;color:#3f535d;font-size:9px;line-height:1.6}.evidence-chunk footer>span{display:flex;align-items:center;gap:4px;color:#6d7c84;font-size:8px}.processing-steps{display:grid}.processing-steps>div{display:grid;grid-template-columns:20px minmax(0,1fr);gap:7px;padding:10px 0;border-bottom:1px solid #e0e6e9;color:#718088}.processing-steps>div.done{color:#286c54}.processing-steps>div span{display:grid;gap:2px}.processing-steps strong{font-size:9px}.processing-steps small{color:#718088;font-size:8px}.upload-fields{margin-top:14px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.form-grid .el-select{width:100%}@media(max-width:1350px){.evidence-layout{grid-template-columns:minmax(570px,58%) minmax(310px,42%)}}
</style>
