<template>
  <div class="product-page"><header class="page-heading"><div><h1>接口与同步</h1><p>管理 HIS、EMR、LIS、药品目录和身份认证连接器，监控版本化字段映射、增量游标与失败重试。</p></div><div class="page-heading-actions"><el-button :icon="Settings2">全局接入策略</el-button><el-button type="primary" :icon="Plus">新增连接器</el-button></div></header><div class="environment-banner"><ServerCog :size="18"/><div><strong>界面预览环境</strong><span>当前页面未连接真实医院接口；所有身份、患者和同步状态均为产品展示数据。</span></div><el-tag type="warning" effect="plain">NON-PRODUCTION</el-tag></div><section class="connector-grid"><article v-for="connector in connectors" :key="connector.id" class="connector-card"><header><div class="connector-icon" :class="connector.className"><component :is="connector.icon" :size="20"/></div><div><strong>{{ connector.name }}</strong><span>{{ connector.type }} · {{ connector.id }}</span></div><span class="status-pill" :class="connector.statusClass"><span class="dot"></span>{{ connector.status }}</span></header><dl><div><dt>同步方式</dt><dd>{{ connector.mode }}</dd></div><div><dt>最近成功</dt><dd>{{ connector.lastSuccess }}</dd></div><div><dt>当前游标</dt><dd>{{ connector.cursor }}</dd></div><div><dt>字段映射</dt><dd>{{ connector.mapping }}</dd></div></dl><footer><span>{{ connector.metric }}</span><div><el-button size="small">查看事件</el-button><el-button size="small" :icon="Settings" circle/></div></footer></article></section><div class="integration-lower"><section class="surface-panel"><div class="surface-panel-header"><h2>最近入站事件</h2><div><span>保留幂等键、版本和载荷哈希</span><el-button size="small" :icon="RefreshCw">刷新</el-button></div></div><table class="dense-table"><thead><tr><th>接收时间</th><th>来源 / 批次</th><th>事件类型</th><th>载荷版本</th><th>状态</th><th>处理结果</th><th>操作</th></tr></thead><tbody><tr v-for="event in events" :key="event.batch"><td>{{ event.time }}</td><td><strong>{{ event.source }}</strong><small>{{ event.batch }}</small></td><td>{{ event.type }}</td><td>{{ event.version }}</td><td><span class="status-pill" :class="event.className"><span class="dot"></span>{{ event.status }}</span></td><td><span>{{ event.result }}</span><small>{{ event.hash }}</small></td><td><el-button size="small" :icon="FileSearch">详情</el-button></td></tr></tbody></table></section><section class="surface-panel mapping-panel"><div class="surface-panel-header"><h2>字段映射版本</h2><el-button size="small" :icon="GitCompareArrows">比较版本</el-button></div><div class="mapping-summary"><div><span>当前发布</span><strong>HIS-CAP-MAP v3.4</strong><small>2026-08-01 · 信息科发布</small></div><div><span>待验证草稿</span><strong>v3.5-draft</strong><small>新增实际用药暴露字段</small></div></div><div class="mapping-diff"><div><span>内部字段</span><strong>MedicationExposure.administeredAt</strong></div><ArrowLeftRight :size="16"/><div><span>来源字段</span><strong>HIS_MED_ADMIN.EXEC_TIME</strong></div></div><div class="mapping-checks"><span><CircleCheck :size="14"/>必填字段 32 / 32</span><span><CircleCheck :size="14"/>枚举映射 18 / 18</span><span class="warning"><TriangleAlert :size="14"/>2 个样本待验证</span></div></section></div></div>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import type { Component } from 'vue'
import { ArrowLeftRight, BookOpen, CircleCheck, Database, FileSearch, GitCompareArrows, HeartPulse, KeyRound, Network, Plus, RefreshCw, ServerCog, Settings, Settings2, TriangleAlert } from 'lucide-vue-next'
import { loadConnectors, loadInboundEvents } from '../services/dataAccess'
import type { ConnectorItem, InboundEventItem } from '../services/dataAccess'

const iconMap = { database: Database, 'heart-pulse': HeartPulse, 'book-open': BookOpen, 'key-round': KeyRound }
type ViewConnector = Omit<ConnectorItem, 'icon'> & { icon: Component }
const connectors = ref<ViewConnector[]>([])
const events = ref<InboundEventItem[]>([])

onMounted(async () => {
  const [c, e] = await Promise.all([loadConnectors(), loadInboundEvents()])
  connectors.value = c.map(item => ({ ...item, icon: iconMap[item.icon as keyof typeof iconMap] ?? Database }))
  events.value = e
})
</script>
<style scoped>
.environment-banner{display:flex;align-items:center;gap:9px;margin-bottom:12px;padding:10px 12px;border:1px solid #decfa9;border-radius:5px;background:#fff9e9;color:#7b5715}.environment-banner>div{min-width:0;flex:1;display:grid;gap:2px}.environment-banner strong{font-size:10px}.environment-banner span{font-size:8px}.connector-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:12px}.connector-card{min-width:0;border:1px solid #d4dde1;border-radius:6px;background:#fff}.connector-card header{display:grid;grid-template-columns:38px minmax(0,1fr) auto;align-items:center;gap:8px;padding:11px;border-bottom:1px solid #dce4e7}.connector-icon{width:36px;height:36px;display:grid;place-items:center;border-radius:5px;background:#e5f0ef;color:#126b66}.connector-icon.blue{background:#ebf2f8;color:#326d9b}.connector-icon.amber{background:#fff4e4;color:#a05a0e}.connector-icon.slate{background:#edf0f2;color:#596b75}.connector-card header>div:nth-child(2){min-width:0;display:grid;gap:2px}.connector-card header strong{font-size:10px}.connector-card header span{color:#728088;font-size:7px}.connector-card dl{display:grid;margin:0;padding:8px 11px}.connector-card dl>div{display:flex;justify-content:space-between;gap:8px;padding:5px 0;border-bottom:1px dashed #e0e6e9}.connector-card dl>div:last-child{border-bottom:0}.connector-card dt,.connector-card dd{margin:0;font-size:8px}.connector-card dt{color:#718088}.connector-card dd{text-align:right}.connector-card footer{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px 11px;background:#f6f8f9;color:#6e7d85;font-size:7px}.connector-card footer>div{display:flex;gap:5px}.integration-lower{display:grid;grid-template-columns:minmax(0,65%) minmax(330px,35%);gap:10px}.surface-panel-header>div{display:flex;align-items:center;gap:8px}.integration-lower td strong,.integration-lower td small{display:block}.integration-lower td small{margin-top:2px;color:#75838a;font-size:7px}.mapping-summary{display:grid;grid-template-columns:1fr 1fr;border-bottom:1px solid #dce4e7}.mapping-summary>div{display:grid;gap:3px;padding:12px}.mapping-summary>div:first-child{border-right:1px solid #dce4e7}.mapping-summary span,.mapping-diff span{color:#718088;font-size:8px}.mapping-summary strong{font-size:10px}.mapping-summary small{color:#74828a;font-size:7px}.mapping-diff{display:grid;grid-template-columns:1fr 20px 1fr;align-items:center;gap:7px;margin:12px;padding:10px;background:#f3f7f8}.mapping-diff>div{min-width:0;display:grid;gap:3px}.mapping-diff strong{overflow-wrap:anywhere;font-size:8px}.mapping-checks{display:grid;gap:7px;padding:0 12px 12px}.mapping-checks span{display:flex;align-items:center;gap:6px;color:#286c54;font-size:8px}.mapping-checks span.warning{color:#9a570d}@media(max-width:1450px){.connector-grid{grid-template-columns:repeat(2,1fr)}.integration-lower{grid-template-columns:minmax(0,60%) minmax(320px,40%)}}
</style>
