<template>
  <div class="product-page">
    <header class="page-heading"><div><h1>知识审核中心</h1><p>对照冻结数据集、统计运行和报告版本审核研究结论；未完成双角色审核的候选不会参与正式推荐。</p></div><div class="page-heading-actions"><el-button :icon="Library">知识库目录</el-button><el-button :icon="RefreshCw" @click="flow.ensureScenario()">刷新待办</el-button></div></header>
    <section class="summary-strip"><div class="summary-item"><div class="summary-icon warning"><Clock3 :size="18"/></div><div><strong>{{ items.length }}</strong><span>待审核候选</span></div></div><div class="summary-item"><div class="summary-icon blue"><UsersRound :size="18"/></div><div><strong>{{ selectedApprovals.length }} / 2</strong><span>当前候选审核角色</span></div></div><div class="summary-item"><div class="summary-icon"><BookOpenCheck :size="18"/></div><div><strong>36</strong><span>已发布知识结论</span></div></div><div class="summary-item"><div class="summary-icon danger"><ShieldAlert :size="18"/></div><div><strong>0</strong><span>违规进入推荐</span></div></div></section>
    <div class="split-workspace knowledge-workspace">
      <section class="split-list"><div class="knowledge-filters"><el-input v-model="query" :prefix-icon="Search" placeholder="搜索结论、报告或数据集"/><el-select v-model="type"><el-option label="全部类型" value="all"/><el-option label="科研结论" value="research"/><el-option label="院内经验" value="experience"/></el-select></div><div class="knowledge-list"><button v-for="item in filteredItems" :key="item.id" :class="{active:selectedId===item.id}" @click="selectedId=item.id"><div><span class="status-pill warning"><span class="dot"></span>{{ item.live?'流程新提交':'待审核' }}</span><small>{{ item.time }}</small></div><strong>{{ item.title }}</strong><p>{{ item.typeLabel }} · {{ item.submitter }}</p><footer><span>{{ item.id }}</span><span>{{ approvals[item.id]?.length||0 }} / 2 角色</span></footer></button></div></section>
      <section v-if="selected" class="split-detail knowledge-detail"><div class="detail-heading"><div><span class="status-pill" :class="selectedApprovals.length===2?'':'warning'"><span class="dot"></span>{{ selectedApprovals.length===2?'双角色审核完成':'待专业审核' }}</span><h2>{{ selected.title }}</h2><p>{{ selected.id }} · {{ selected.time }} · {{ selected.submitter }}</p></div><el-button :icon="MoreHorizontal" circle/></div>
        <div class="knowledge-warning"><ShieldAlert :size="17"/><span>{{ selectedApprovals.length===2?'当前演示候选已完成两角色审核，但仍明确标记为合成验证知识，不参与正式处方推荐。':'当前内容是知识候选；临床药师与研究负责人分别批准前不会发布，也不会参与处方推荐。' }}</span></div>
        <el-tabs v-model="tab"><el-tab-pane label="结论与适用范围" name="conclusion"><div class="conclusion-box"><span>候选结论</span><p>{{ selected.conclusion }}</p></div><dl class="knowledge-meta"><div><dt>适用范围</dt><dd>{{ selected.applicability }}</dd></div><div><dt>数据集与报告</dt><dd><button>{{ selected.dataset }}</button><button>{{ selected.report }}</button></dd></div><div><dt>样本量</dt><dd>{{ selected.sampleSize }} 例合成验证记录</dd></div><div><dt>发表支撑</dt><dd>ZIP 数据包 + DOCX 医学报告 · {{ selected.reportingGuideline }}</dd></div><div><dt>伦理与注册</dt><dd>{{ selected.ethicsApproval }}</dd></div><div><dt>证据等级</dt><dd>演示科研结论 · 不用于临床决策</dd></div><div><dt>已知限制</dt><dd>{{ selected.limitations }}</dd></div><div><dt>不适用范围</dt><dd>正式科研、因果推断、临床指南或自动推荐规则</dd></div></dl></el-tab-pane>
          <el-tab-pane label="数据与报告对照" name="source"><div class="source-comparison"><section><div><Database :size="16"/><strong>冻结数据集</strong></div><p>{{ selected.dataset }}<br/>输入哈希 {{ selected.inputHash }}<br/>{{ selected.sampleSize }} 条纳入记录</p><el-button size="small" @click="$router.push('/research/workbench')">查看队列与变量</el-button></section><section><div><FileText :size="16"/><strong>统计、数据包与报告</strong></div><p>{{ selected.runId }}<br/>输出哈希 {{ selected.outputHash }}<br/>ZIP + {{ selected.report }}.docx</p><el-button size="small" @click="$router.push('/research/workbench')">查看并下载交付物</el-button></section><section><div><Library :size="16"/><strong>投稿就绪门禁</strong></div><p>{{ selected.reportingGuideline }}<br/>伦理/注册待核验<br/>合成数据禁止投稿</p></section></div></el-tab-pane>
          <el-tab-pane label="审核记录" name="history"><div class="approval-timeline"><div class="done"><CircleCheck :size="16"/><span><strong>提交前校验</strong><small>数据集冻结、固定统计、报告审核均完成</small></span></div><div :class="{done:selectedApprovals.includes('pharmacist'),active:!selectedApprovals.includes('pharmacist')}"><component :is="selectedApprovals.includes('pharmacist')?CircleCheck:Clock3" :size="16"/><span><strong>临床药师审核</strong><small>{{ selectedApprovals.includes('pharmacist')?'已记录审核':'等待临床药师处理' }}</small></span></div><div :class="{done:selectedApprovals.includes('research_director'),active:selectedApprovals.includes('pharmacist')&&!selectedApprovals.includes('research_director')}"><component :is="selectedApprovals.includes('research_director')?CircleCheck:Circle" :size="16"/><span><strong>研究负责人审核</strong><small>{{ selectedApprovals.includes('research_director')?'已记录审核':'等待研究负责人处理' }}</small></span></div></div></el-tab-pane></el-tabs>
        <div class="knowledge-decision"><label><span>审核意见 <em>必填</em></span><el-input v-model="note" type="textarea" :rows="2" placeholder="说明结论边界、适用范围或退回原因"/></label><div><el-button :icon="RotateCcw" @click="recordDecision('return')">退回修改</el-button><el-button type="danger" plain :icon="XCircle" @click="recordDecision('reject')">不通过</el-button><el-button type="primary" :icon="CheckCircle2" :disabled="!note||selectedApprovals.length===2" @click="approveNextRole">批准{{ nextRoleLabel }}</el-button></div><el-alert v-if="decisionMessage" type="success" :title="decisionMessage" :closable="false"/></div>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { BookOpenCheck, CheckCircle2, Circle, CircleCheck, Clock3, Database, FileText, Library, MoreHorizontal, RefreshCw, RotateCcw, Search, ShieldAlert, UsersRound, XCircle } from 'lucide-vue-next'
import { useFlowSimulationStore } from '../stores/flowSimulation'
import { loadKnowledgeSubmissions, submitKnowledgeReview } from '../services/dataAccess'

interface KnowledgeItem {id:string;title:string;type:string;typeLabel:string;submitter:string;time:string;live:boolean;dataset:string;report:string;sampleSize:number;conclusion:string;limitations:string;applicability:string;inputHash:string;outputHash:string;runId:string;reportingGuideline:string;ethicsApproval:string}
const flow=useFlowSimulationStore();const query=ref('');const type=ref('all');const selectedId=ref('KS-2026-014');const tab=ref('conclusion');const note=ref('');const decisionMessage=ref('');const approvals=reactive<Record<string,string[]>>({});const realItems=ref<KnowledgeItem[]>([]);const isPreview=import.meta.env.VITE_UI_PREVIEW==='true'
const legacyItems:KnowledgeItem[]=[{id:'KS-2026-014',title:'CAP 住院患者初始方案院内观察结论',type:'research',typeLabel:'科研结论',submitter:'研究负责人·周医生',time:'08-03 09:20',live:false,dataset:'DS-CAP-v6',report:'RPT-CAP-006-v2',sampleSize:128,conclusion:'当前合成验证队列仅用于检查数据与审核链路，不能解释为疗效优越或推广性结论。',limitations:'非真实患者、无因果推断、随访存在缺失',applicability:'呼吸内科 · 成人住院 CAP · 演示验证',inputHash:'36df...b821',outputHash:'8b72...09de',runId:'RUN-CAP-019',reportingGuideline:'STROBE',ethicsApproval:'演示记录，非正式伦理批件'}]
const liveItem=computed<KnowledgeItem|null>(()=>flow.knowledgeStatus==='review_pending'&&flow.scenario?{id:`KS-${flow.reportVersion}`,title:flow.scenario.research.reportTemplate.title,type:'research',typeLabel:'科研结论',submitter:`研究负责人·${flow.scenario.research.project.owner}`,time:new Date().toLocaleString('zh-CN',{hour12:false}),live:true,dataset:flow.datasetVersion,report:flow.reportVersion,sampleSize:flow.analysisResult?.sampleSize??0,conclusion:flow.reportSections.conclusion||'',limitations:flow.reportSections.limitations||'',applicability:flow.scenario.research.reportTemplate.applicability,inputHash:flow.datasetHash,outputHash:flow.analysisResult?.outputHash||'',runId:flow.analysisResult?.runId||'',reportingGuideline:flow.scenario.research.publicationProfile.reportingGuideline,ethicsApproval:flow.scenario.research.publicationProfile.ethicsApproval}:null)
const items=computed(()=>{
  if(!isPreview)return realItems.value
  return liveItem.value?[liveItem.value,...legacyItems]:legacyItems
})
function mapSubmission(s: {submissionId:string;reportId:string;status:string;submissionType:string;title:string;submittedBy:string;submittedAt:string;reviewedRoles?:string[]}):KnowledgeItem{
  return {id:s.submissionId,title:s.title||s.reportId,type:'research',typeLabel:'科研结论',submitter:s.submittedBy||'待确认',time:s.submittedAt?.slice(0,16)||'',live:false,dataset:s.reportId,report:s.reportId,sampleSize:0,conclusion:`提交状态：${s.status}`,limitations:'后端未返回详细结论字段',applicability:'',inputHash:'',outputHash:'',runId:'',reportingGuideline:'',ethicsApproval:''}
}
async function loadReal(){try{const subs=await loadKnowledgeSubmissions();realItems.value=subs.map(mapSubmission);if(!selectedId.value&&realItems.value.length)selectedId.value=realItems.value[0].id}catch(e){realItems.value=[];decisionMessage.value=`真实知识队列加载失败：${(e as Error).message}`}}
const filteredItems=computed(()=>items.value.filter(item=>(type.value==='all'||item.type===type.value)&&(!query.value||`${item.title} ${item.id} ${item.report}`.toLowerCase().includes(query.value.toLowerCase()))));const selected=computed(()=>items.value.find(item=>item.id===selectedId.value)??items.value[0]);const selectedApprovals=computed(()=>approvals[selected.value?.id||'']??[]);const nextRoleLabel=computed(()=>selectedApprovals.value.includes('pharmacist')?'研究负责人审核':'临床药师审核')
async function approveNextRole(){if(!selected.value||!note.value)return;const role=selectedApprovals.value.includes('pharmacist')?'research_director':'pharmacist';if(!isPreview){try{await submitKnowledgeReview(selected.value.id,role,'approve',note.value);decisionMessage.value=`已提交${role==='pharmacist'?'临床药师':'研究负责人'}审核`;await loadReal();note.value=''}catch(e){decisionMessage.value=`审核提交失败：${(e as Error).message}`;return}}else{(approvals[selected.value.id]??=[]).push(role);flow.addAudit('knowledge',`KNOWLEDGE_${role.toUpperCase()}_APPROVED`,selected.value.id);flow.persist();decisionMessage.value=`已记录${role==='pharmacist'?'临床药师':'研究负责人'}审核；${approvals[selected.value.id].length===2?'双角色审核完成':'等待下一角色审核'}。`;note.value=''}}
function recordDecision(action:string){if(!selected.value||!note.value){if(!note.value)decisionMessage.value='请填写退回原因';return}if(!isPreview){const decision=action==='approve'?'approve':'reject';submitKnowledgeReview(selected.value.id,nextRoleLabel.value==='研究负责人审核'?'research_director':'pharmacist',decision,note.value).then(async()=>{decisionMessage.value=`已提交“${action==='reject'?'不通过':'退回修改'}”`;await loadReal();note.value=''}).catch((e:Error)=>{decisionMessage.value=`审核提交失败：${e.message}`})}else{decisionMessage.value=`已记录“${action}”处理；前端演示不会删除原始报告与审核记录。`}}
watch(liveItem,item=>{if(item)selectedId.value=item.id},{immediate:true});onMounted(async()=>{if(!isPreview)await loadReal();else flow.ensureScenario()})
</script>

<style scoped>
.knowledge-workspace{height:calc(100vh - 196px);min-height:610px}.knowledge-filters{display:grid;grid-template-columns:minmax(0,1fr) 120px;gap:6px;padding:9px;border-bottom:1px solid #dce4e7;background:#fff}.knowledge-list>button{width:100%;display:grid;gap:7px;padding:12px;border:0;border-bottom:1px solid #dce4e7;background:transparent;color:#273a43;text-align:left;cursor:pointer}.knowledge-list>button.active{background:#eaf3f2;box-shadow:inset 3px 0 #126b66}.knowledge-list>button>div,.knowledge-list footer{display:flex;justify-content:space-between;gap:8px}.knowledge-list small,.knowledge-list footer{color:#728088;font-size:8px}.knowledge-list strong{font-size:10px}.knowledge-list p{margin:0;color:#697981;font-size:8px}.knowledge-detail{overflow:auto}.detail-heading{display:flex;justify-content:space-between;gap:10px;padding-bottom:11px;border-bottom:1px solid #dce4e7}.detail-heading h2{margin:7px 0 3px;font-size:15px}.detail-heading p{margin:0;color:#6b7a82;font-size:8px}.knowledge-warning{display:flex;gap:8px;margin:11px 0;padding:9px;background:#fff7e8;color:#815018;font-size:8px;line-height:1.5}.conclusion-box{padding:12px;border-left:4px solid #126b66;background:#edf5f4}.conclusion-box span{color:#126b66;font-size:8px;font-weight:750}.conclusion-box p{margin:6px 0 0;font-size:10px;line-height:1.65}.knowledge-meta{display:grid;margin:12px 0 0;border:1px solid #dce4e7}.knowledge-meta>div{display:grid;grid-template-columns:120px 1fr;border-bottom:1px solid #dce4e7}.knowledge-meta dt,.knowledge-meta dd{margin:0;padding:8px 10px;font-size:9px}.knowledge-meta dt{background:#f4f7f8;color:#687880}.knowledge-meta dd button{margin-right:5px;padding:0;border:0;background:transparent;color:#246b8c}.source-comparison{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.source-comparison section{padding:11px;border:1px solid #dce4e7;background:#f8fafb}.source-comparison section>div{display:flex;align-items:center;gap:6px}.source-comparison strong{font-size:9px}.source-comparison p{color:#66777f;font-size:8px;line-height:1.65}.approval-timeline>div{display:grid;grid-template-columns:22px 1fr;gap:7px;padding:10px 0;border-bottom:1px solid #dfe6e9;color:#7a878e}.approval-timeline>div.done{color:#287056}.approval-timeline>div.active{color:#a05a0d}.approval-timeline span{display:grid;gap:2px}.approval-timeline strong{font-size:9px}.approval-timeline small{font-size:8px}.knowledge-decision{margin-top:12px;padding-top:11px;border-top:1px solid #dce4e7}.knowledge-decision label>span{display:block;margin-bottom:4px;color:#687880;font-size:8px}.knowledge-decision em{color:#bd2f37;font-style:normal}.knowledge-decision>div{display:flex;justify-content:flex-end;gap:7px;margin-top:8px}.knowledge-decision .el-alert{margin-top:8px}
</style>
