<template>
  <div class="product-page timeline-page">
    <header class="page-heading"><div><h1>长期用药追踪</h1><p>按就诊分段展示用药、检验、症状、不良反应、医生调整和结局并行轨道。</p></div><div class="page-heading-actions"><el-button :icon="Filter">筛选轨道</el-button><el-button :icon="MessageSquarePlus">记录用药反馈</el-button><el-button type="primary" :icon="Stethoscope" @click="$router.push('/doctor/workbench/E001')">返回当前决策</el-button></div></header>
    <section class="timeline-patient-bar surface-panel"><div><strong>合成患者A</strong><span>女 · 66岁 · P001</span></div><div class="timeline-legend"><span v-for="item in legends" :key="item.label"><i :style="{ background: item.color }"></i>{{ item.label }}</span></div><el-select v-model="range" size="small"><el-option label="近 2 年" value="2y" /><el-option label="全部记录" value="all" /></el-select></section>
    <section class="longitudinal surface-panel">
      <div class="encounter-segment current"><div class="encounter-header"><div><span class="encounter-date">2026-08-03 — 当前</span><h2>呼吸内科住院 · E001</h2><p>社区获得性肺炎 · 数据版本 v3</p></div><div class="encounter-state"><span class="status-pill warning"><span class="dot"></span>治疗中</span><strong>住院第 1 天</strong></div></div><div class="tracks"><div v-for="track in currentTracks" :key="track.name" class="track-row"><div class="track-label"><component :is="track.icon" :size="15" />{{ track.name }}</div><div class="track-lane"><article v-for="event in track.events" :key="event.time + event.title" :class="track.className"><time>{{ event.time }}</time><strong>{{ event.title }}</strong><span>{{ event.detail }}</span><small>{{ event.source }}</small></article></div></div></div></div>
      <div class="risk-link"><ShieldAlert :size="17" /><div><strong>历史事件正在影响当前推荐</strong><span>2025-11 的有效方案被作为排序参考；由于当时适用条件不完整，不能直接复用为规则。</span></div><el-button size="small" @click="$router.push('/doctor/workbench/E001')">查看关联推荐</el-button></div>
      <div v-for="encounter in historicalEncounters" :key="encounter.id" class="encounter-segment"><div class="encounter-header"><div><span class="encounter-date">{{ encounter.date }}</span><h2>{{ encounter.title }}</h2><p>{{ encounter.diagnosis }}</p></div><div class="encounter-state"><span class="status-pill"><span class="dot"></span>{{ encounter.outcome }}</span><strong>{{ encounter.duration }}</strong></div></div><div class="compact-event-grid"><article v-for="event in encounter.events" :key="event.title" :class="event.className"><div><component :is="event.icon" :size="15" /><span>{{ event.type }}</span></div><strong>{{ event.title }}</strong><p>{{ event.detail }}</p><small>{{ event.source }}</small></article></div></div>
    </section>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue'
import { Activity, ClipboardPlus, FileCheck2, Filter, FlaskConical, MessageSquarePlus, Pill, ShieldAlert, Stethoscope, Thermometer } from 'lucide-vue-next'
const range=ref('2y')
const legends=[{label:'用药',color:'#2f7f79'},{label:'检验',color:'#3974a3'},{label:'症状',color:'#9c631b'},{label:'不良反应',color:'#b7333b'},{label:'调整与结局',color:'#65747c'}]
const currentTracks=[
 {name:'用药',icon:Pill,className:'med-event',events:[{time:'08:35',title:'0.9%氯化钠注射液',detail:'静脉滴注 · 当前有效',source:'HIS医嘱 ORD-001'},{time:'待决策',title:'抗感染候选方案',detail:'3 个候选等待医生审核',source:'HospitalAI REC-E001-v3'}]},
 {name:'检验',icon:FlaskConical,className:'lab-event',events:[{time:'08:50',title:'CRP 42 mg/L',detail:'异常，较前下降',source:'LIS LIS-001'},{time:'08:50',title:'肌酐 76 umol/L',detail:'当前稳定',source:'LIS LIS-002'}]},
 {name:'症状',icon:Thermometer,className:'symptom-event',events:[{time:'08:20',title:'咳嗽、发热',detail:'入院症状记录',source:'EMR 病程记录'}]},
 {name:'调整',icon:ClipboardPlus,className:'adjust-event',events:[{time:'10:24',title:'待医生完成处方决策',detail:'处方草稿尚未生成',source:'HospitalAI 待办'}]}
]
const historicalEncounters=[
 {id:'E-2025-11',date:'2025-11-02 — 2025-11-09',title:'呼吸内科住院 · E-2025-11',diagnosis:'细菌性肺炎',outcome:'好转出院',duration:'7 天',events:[{type:'用药',icon:Pill,title:'阿莫西林克拉维酸钾',detail:'完成 7 天疗程，未记录不良反应。',source:'HIS医嘱 + 出院带药',className:'med-event'},{type:'疗效',icon:Activity,title:'症状与炎症指标改善',detail:'CRP 由 68 降至 16 mg/L。',source:'LIS + 出院小结',className:'lab-event'},{type:'结局',icon:FileCheck2,title:'好转出院',detail:'出院带药 3 天，随访未回传。',source:'出院小结',className:'adjust-event'}]},
 {id:'E-2024-03',date:'2024-03-18',title:'呼吸内科门诊 · E-2024-03',diagnosis:'下呼吸道感染',outcome:'记录不完整',duration:'1 次门诊',events:[{type:'用药',icon:Pill,title:'口服抗感染方案',detail:'实际用药暴露未确认。',source:'门诊处方',className:'med-event'},{type:'反馈',icon:MessageSquarePlus,title:'疗效反馈缺失',detail:'不作为当前有效方案依据。',source:'缺失状态',className:'symptom-event'}]}
]
</script>
<style scoped>
.timeline-patient-bar{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:20px;margin-bottom:14px;padding:11px 14px}.timeline-patient-bar>div:first-child{display:grid;gap:2px}.timeline-patient-bar strong{font-size:11px}.timeline-patient-bar span{color:#687880;font-size:9px}.timeline-legend{display:flex;justify-content:center;gap:16px;flex-wrap:wrap}.timeline-legend span{display:inline-flex;align-items:center;gap:5px}.timeline-legend i{width:7px;height:7px;border-radius:2px}.longitudinal{padding:16px}.encounter-segment{padding:0 0 20px;margin-bottom:20px;border-bottom:1px solid #d9e2e5}.encounter-segment:last-child{border-bottom:none;margin-bottom:0}.encounter-header{display:flex;align-items:flex-start;justify-content:space-between;gap:15px;margin-bottom:12px}.encounter-date{color:#126b66;font-size:9px;font-weight:750}.encounter-header h2{margin:3px 0;font-size:14px}.encounter-header p{margin:0;color:#697981;font-size:9px}.encounter-state{display:grid;justify-items:end;gap:5px}.encounter-state>strong{font-size:9px}.tracks{display:grid;border:1px solid #d9e2e5;border-radius:5px;overflow:hidden}.track-row{display:grid;grid-template-columns:84px minmax(0,1fr);border-bottom:1px solid #dfe6e9}.track-row:last-child{border-bottom:none}.track-label{display:flex;align-items:flex-start;gap:6px;padding:11px 9px;background:#f4f7f8;color:#52656f;font-size:9px;font-weight:700}.track-lane{min-width:0;display:flex;gap:8px;padding:8px;overflow-x:auto}.track-lane article,.compact-event-grid article{min-width:185px;padding:8px 9px;border:1px solid #d8e1e4;border-left:3px solid #65747c;border-radius:4px;background:#fff}.track-lane time{display:block;color:#718088;font-size:8px}.track-lane strong,.compact-event-grid strong{display:block;margin-top:3px;font-size:10px}.track-lane span{display:block;margin-top:2px;color:#53666f;font-size:8px}.track-lane small,.compact-event-grid small{display:block;margin-top:5px;color:#7c8990;font-size:7px}.med-event{border-left-color:#2f7f79!important}.lab-event{border-left-color:#3974a3!important}.symptom-event{border-left-color:#9c631b!important}.adjust-event{border-left-color:#65747c!important}.risk-link{display:flex;align-items:center;gap:9px;margin:-7px 0 20px;padding:10px;border:1px solid #ebd2aa;border-radius:5px;background:#fff7e9;color:#825018}.risk-link>div{min-width:0;flex:1;display:grid;gap:2px}.risk-link strong{font-size:10px}.risk-link span{font-size:8px;line-height:1.45}.compact-event-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.compact-event-grid article{min-width:0}.compact-event-grid article>div{display:flex;align-items:center;gap:5px;color:#65757d;font-size:8px}.compact-event-grid p{margin:4px 0 0;color:#53666f;font-size:8px;line-height:1.45}@media(max-width:1350px){.compact-event-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
</style>
