<template>
  <div class="product-page">
    <header class="page-heading"><div><h1>临床规则管理</h1><p>规则草稿、病例测试、双人审核、发布与撤回全程版本化；AI 不能发布医学规则。</p></div><div class="page-heading-actions"><el-button :icon="Upload">导入规则包</el-button><el-button type="primary" :icon="Plus" @click="editVisible=true">新建规则草稿</el-button></div></header>
    <section class="summary-strip"><div class="summary-item"><div class="summary-icon"><GitBranch :size="18" /></div><div><strong>24</strong><span>已发布规则</span></div></div><div class="summary-item"><div class="summary-icon warning"><ClipboardClock :size="18" /></div><div><strong>3</strong><span>待审核版本</span></div></div><div class="summary-item"><div class="summary-icon blue"><TestTube2 :size="18" /></div><div><strong>126 / 126</strong><span>规则病例通过</span></div></div><div class="summary-item"><div class="summary-icon danger"><CircleAlert :size="18" /></div><div><strong>1</strong><span>受影响知识待复核</span></div></div></section>
    <div class="toolbar-band"><el-input v-model="query" :prefix-icon="Search" placeholder="规则编号、名称或药品" clearable/><el-select v-model="status"><el-option label="全部状态" value="all"/><el-option label="已发布" value="published"/><el-option label="待审核" value="review"/><el-option label="草稿" value="draft"/></el-select><el-select v-model="severity"><el-option label="全部等级" value="all"/><el-option label="阻断" value="block"/><el-option label="强提醒" value="strong"/><el-option label="一般提示" value="info"/></el-select><span class="toolbar-spacer"></span><el-button :icon="FileDown">导出规则清单</el-button></div>
    <section class="surface-panel rules-panel"><div class="surface-panel-header"><h2>规则与版本</h2><span>{{ filteredRules.length }} 条 · 已发布版本只读</span></div><table class="dense-table"><thead><tr><th>规则编号 / 名称</th><th>风险等级</th><th>当前版本</th><th>状态</th><th>规则病例</th><th>依据</th><th>更新人 / 时间</th><th>操作</th></tr></thead><tbody><tr v-for="rule in filteredRules" :key="rule.id"><td><strong>{{ rule.id }}</strong><span class="rule-name">{{ rule.name }}</span><small>{{ rule.scope }}</small></td><td><span class="status-pill" :class="rule.severityClass"><span class="dot"></span>{{ rule.severity }}</span></td><td><strong>{{ rule.version }}</strong><small>{{ rule.previous }}</small></td><td><span class="status-pill" :class="rule.statusClass"><span class="dot"></span>{{ rule.statusLabel }}</span></td><td><strong>{{ rule.cases }}</strong><small>最近回归 {{ rule.testAt }}</small></td><td><button class="evidence-ref">{{ rule.evidence }} <ExternalLink :size="11" /></button></td><td><span>{{ rule.updatedBy }}</span><small>{{ rule.updatedAt }}</small></td><td><div class="table-actions"><el-button size="small" @click="openRule(rule)">查看</el-button><el-dropdown><el-button size="small" :icon="MoreHorizontal" circle/><template #dropdown><el-dropdown-menu><el-dropdown-item>创建新版本</el-dropdown-item><el-dropdown-item>查看命中记录</el-dropdown-item><el-dropdown-item divided :disabled="rule.status!=='published'">发起撤回</el-dropdown-item></el-dropdown-menu></template></el-dropdown></div></td></tr></tbody></table></section>
    <el-drawer v-model="drawerVisible" size="560px" title="规则版本详情"><div v-if="activeRule" class="rule-detail"><div class="rule-detail-heading"><div><span class="status-pill" :class="activeRule.severityClass"><span class="dot"></span>{{ activeRule.severity }}</span><h2>{{ activeRule.name }}</h2><p>{{ activeRule.id }} · {{ activeRule.version }} · {{ activeRule.statusLabel }}</p></div><el-button :icon="Copy">复制为新版本</el-button></div><el-alert type="warning" title="这是演示规则定义；正式发布必须完成药师与临床专家审核。" :closable="false" show-icon/><h3>机器可读条件</h3><pre>{
  "fact": "confirmed_allergy",
  "operator": "matches_candidate_drug",
  "result": "BLOCK",
  "overridable": false
}</pre><h3>命中结果与用户提示</h3><div class="result-preview"><ShieldX :size="18"/><div><strong>已确认药物过敏：后续就诊必须继承并阻断</strong><span>输出包含规则编号、版本、命中事实和不可绕过标记。</span></div></div><h3>审核链路</h3><div class="approval-flow"><div class="done"><CircleCheck :size="15"/><span><strong>药师审核</strong><small>陈药师 · 2026-08-01 14:22</small></span></div><ChevronRight :size="15"/><div class="done"><CircleCheck :size="15"/><span><strong>临床专家审核</strong><small>周医生 · 2026-08-02 09:18</small></span></div><ChevronRight :size="15"/><div class="done"><CircleCheck :size="15"/><span><strong>发布</strong><small>2026-08-02 10:00</small></span></div></div><h3>规则病例</h3><table class="dense-table"><thead><tr><th>病例</th><th>输入</th><th>期望</th><th>结果</th></tr></thead><tbody><tr><td>ALG-001</td><td>确认过敏 + 同药候选</td><td>BLOCK</td><td><span class="status-pill"><span class="dot"></span>通过</span></td></tr><tr><td>ALG-002</td><td>未确认过敏</td><td>PASS</td><td><span class="status-pill"><span class="dot"></span>通过</span></td></tr></tbody></table></div></el-drawer>
    <el-dialog v-model="editVisible" title="新建规则草稿" width="620px"><el-form label-position="top"><div class="form-grid"><el-form-item label="规则编号"><el-input placeholder="HR-XXX-001"/></el-form-item><el-form-item label="风险等级"><el-select><el-option label="阻断" value="block"/><el-option label="强提醒" value="strong"/><el-option label="一般提示" value="info"/></el-select></el-form-item></div><el-form-item label="规则名称"><el-input placeholder="清晰描述规则目标"/></el-form-item><el-form-item label="适用范围"><el-input placeholder="病种、科室、药品或患者条件"/></el-form-item><el-alert type="info" title="保存后状态为草稿，不能参与正式推荐。" :closable="false"/></el-form><template #footer><el-button @click="editVisible=false">取消</el-button><el-button type="primary" @click="editVisible=false">保存草稿</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ChevronRight, CircleAlert, CircleCheck, Clock3 as ClipboardClock, Copy, ExternalLink, FileDown, GitBranch, MoreHorizontal, Plus, Search, ShieldX, TestTube2, Upload } from 'lucide-vue-next'
import { loadRules } from '../services/dataAccess'
import type { RuleItem } from '../services/dataAccess'
const query=ref(''),status=ref('all'),severity=ref('all'),drawerVisible=ref(false),editVisible=ref(false),activeRule=ref<RuleItem|null>(null),loading=ref(false)
const rules=ref<RuleItem[]>([])
async function fetchRules(){loading.value=true;try{rules.value=await loadRules()}finally{loading.value=false}}
const filteredRules=computed(()=>rules.value.filter(r=>(!query.value||`${r.id}${r.name}${r.evidence}`.includes(query.value))&&(status.value==='all'||r.status===status.value)&&(severity.value==='all'||r.severityClass===severity.value)))
function openRule(rule:RuleItem){activeRule.value=rule;drawerVisible.value=true}
onMounted(fetchRules)
</script>
<style scoped>
.rules-panel{overflow-x:auto}.rules-panel table{min-width:1120px}.rules-panel td:first-child strong,.rule-name,.rules-panel td small{display:block}.rule-name{margin-top:3px;font-size:10px}.rules-panel td small{margin-top:3px;color:#73828a;font-size:8px}.evidence-ref{display:flex;align-items:center;gap:3px;padding:0;border:0;background:transparent;color:#286a88;font-size:9px;cursor:pointer}.table-actions{display:flex;gap:5px}.rule-detail-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:14px}.rule-detail-heading h2{margin:7px 0 3px;font-size:16px}.rule-detail-heading p{margin:0;color:#6b7b83;font-size:9px}.rule-detail h3{margin:18px 0 7px;font-size:11px}.rule-detail pre{margin:0;padding:12px;overflow:auto;border-radius:5px;background:#17252d;color:#dbe7e9;font-size:10px;line-height:1.55}.result-preview{display:flex;gap:8px;padding:10px;border-left:4px solid #bd2f37;background:#fff1f1;color:#8d2229}.result-preview>div{display:grid;gap:3px}.result-preview strong{font-size:10px}.result-preview span{font-size:8px}.approval-flow{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;align-items:center;gap:7px}.approval-flow>div{display:flex;align-items:center;gap:6px;padding:8px;border:1px solid #d8e1e4;border-radius:4px}.approval-flow>div.done{color:#286c54}.approval-flow>div span{display:grid;gap:2px}.approval-flow strong{font-size:9px}.approval-flow small{color:#6f7f87;font-size:7px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.form-grid .el-select{width:100%}
</style>
